config/routes.rb
Rails.application.routes.draw do
  resources :items

  devise_for :users
  root 'pages#home'

  get 'adminpanel' => 'pages#adminpanel'

  post '/buy/:slug', to: 'transactions#create', as: :buy
  get '/pickup/:guid', to: 'transactions#pickup', as: :pickup

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
       can :read, :all
       can :manage, Item do |item|
            item.try(:user) == user
        end
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  extend FriendlyId
 friendly_id :name, use: :slugged
   belongs_to :user
   has_many :sales
   has_attached_file :image

      validates_attachment_content_type :image,
      content_type:  /^image\/(png|gif|jpeg)/,
      message: "Only images allowed"

      validates :image, attachment_presence: true

      validates_numericality_of :price,
      greather_then: 1.00, message: "Must be at least 1 Dollar"

end

app/models/sale.rb
class Sale < ActiveRecord::Base

	before_create :populate_guid
	belongs_to :item

	include AASM

	aasm column: 'state' do
		state :pending, initial: true
		state :processing
		state :finished
		state :errored

		event :process, after: :charge_card do
		transitions from: :pending, to: :processing
	end

	event :finish do
		transitions from: :processing, to: :finished
	end

	event :fail do
		transitions from: :processing, to: :errored
	end
	end


	def charge_card
		begin
			save!
			charge = Stripe::Charge.create(
				amount: self.amount,
				currency: "aud",
				card: self.stripe_token,
				description: "Item Sale"
				)
			self.update(stripe_id: charge.id)
			self.finish!
		rescue Stripe::StripeError => e
			self.update_attributes(error: e.message)
			self.fail!
		end
	end

	private

		def populate_guid
			self.guid = SecureRandom.uuid()
		end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  rescue_from CanCan::AccessDenied do |exception|
  redirect_to root_path, notice: "You are not authorized to access this area"
end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user! , only: [:new, :edit, :create, :update, :destroy]
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.where(availability: true)
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
  @item = Item.new
  end

  # GET /items/1/edit
  def edit
    authorize! :manage, @item
  end

  # POST /items
  # POST /items.json
  def create
    @item = current_user.items.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    authorize! :manage, @item

    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    authorize! :manage, @item
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.friendly.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :seller, :desciption, :price, :availability, :image)

    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [:adminpanel]

  def home
    if current_user
      redirect_to items_path
    end
    @items =Item.last(10)
  end

  def adminpanel
    @items = current_user.items
    @purchased = Sale.where(buyer_email: current_user.email)
    @sales = Sale.where(seller_email: current_user.email)

  end
end

app/controllers/transactions_controller.rb
class TransactionsController< ApplicationController

	def create
		item = Item.find_by!(slug: params[:slug])
		sale = item.sales.create(
			amount: item.price,
			buyer_email: current_user.email,
			seller_email: item.user.email,
			stripe_token: params[:stripeToken])
		sale.process!
		if sale.finished?
			redirect_to pickup_url(guid: sale.guid), notice: "Transitions Successful"
		else
			redirect_to pickup_url(guid: sale.guid), notice: "Transitions Successful"
		end 

	end

	def pickup
		@sale = Sale.find_by!(guid: params[:guid])
		@item = @sale.item
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/items/_form.html.erb
<%= simple_form_for(@item, html: {class: "form-signin"}) do |f| %>
  <%= f.error_notification %>

  <%= f.input :name, required: true, label: false, placeholder: "Product Name", input_html: { class: "form-control"} %>
   <%= f.input :seller, required: true, label: false, placeholder: "Seller", input_html: { class: "form-control"} %>
   <%= f.input :desciption, required: true, label: false, placeholder: "desciption", input_html: { class: "form-control"}, rows: 5 %>
   <%= f.input :price, required: true, label: false, placeholder: "Price", input_html: { class: "form-control"} %>
   <%= f.input :availability %>
  <%= f.input :image %>
  </div>


  <%= f.button :submit, class: "btn btn-primary btn-block" %>

<% end %>

app/views/items/_item.html.erb
<div class="col-md-3">
  <div class="thumbnail">
    <%= link_to item_path(item) do %>
    <%= image_tag item.image.url(:original), class: "img-responsive" %>
    <% end %>
  <div class="caption"
  <p><strong><%= link_to item.name, item_path(item) %></strong></p>
      <p>$<%= item.price.to_f / 100 %></p>
  </div>
</div>
</div>

app/views/items/edit.html.erb
<h1 class="text-center">Edit Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<div class="row">

  <%= render @items %>

</div>

app/views/items/new.html.erb
<h1 class="text-center">New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<div class="container">
	<div class="row">

		<div class="col-md-6">
			<%= image_tag @item.image.url(:original), class: "img-responsive" %>
		</div>

		<div class="col-md-6">
			<h3><%= @item.name %> by <%= @item.seller %></h3>
			<p class="justify"><%= @item.desciption %></p>
			<h4 class="text-right">$<%= @item.price.to_f / 100 %></h4>

			<% if current_user %>

			<%= form_tag buy_path(slug: @item.slug) do  %>
			<script
				src="https://checkout.stripe.com/checkout.js" class="stripe-button"
				data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
				data-amount="	<%= @item.price %>"
				data-name="app"
				data-description=" <%= @item.name %>"
				data-email="<%= current_user.email %>"
				data-locale="auto">
			</script>
		<% end %>
		<% else %>
			<p>Please login to Buy Item</p>
		<% end %>
		</div>

	</div>
</div>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "oneverr", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


      <ul class="nav navbar-nav navbar-right">

        <li><%= link_to "Item", items_path %></li>

        <% if current_user %>

          <li><%= link_to "Settings", edit_user_registration_path %></li>
          <li><%= link_to "Adminpanel", adminpanel_path %></li>

           <li><%= link_to "Logout", destroy_user_session_path, method: :delete %>

        <% else %>

          <li><%= link_to "Login", new_user_session_path %></li>

        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <% flash.each do |type, message| %>
    <div class="alert alert-info fade-in">
     <button class="close" data-dismiss="alert">X</button>
     <%= message %>
     </div>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/_items.html.erb
<table class="table table-condensed">
	<thead>
		<tr>
			<th>Id</th>
			<th>Name</th>
			<th>Available</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @items.each do |item| %>
		<tr>
			<td><%= item.id %></td>
			<td><%= link_to item.name, item_path(item) %></td>
			<td><%= item.availability %></td>
			<td><%= link_to "edit", edit_item_path(item) %></td>
		</tr>
		<% end %>
 </tbody>
</table>

app/views/pages/_purchased.html.erb
<table class="table table-condensed">
	<thead>
		<tr>
			<th>Name</th>
			<th>Date</th>
		</tr>
	</thead>

	<tbody>
		<% @purchased.each do |sale| %>
		<tr>
			<td><%= link_to sale.item.name, pickup_path(sale.guid) %></td>
			<td><%= time_ago_in_words(sale.created_at) %> ago</td>
		</tr>
		<% end %>
 </tbody>
</table>

app/views/pages/_sales.html.erb
<table class="table table-condensed">
	<thead>
		<tr>
			<th>Name</th>
			<th>Date</th>
			<th>Buyer</th>
		</tr>
	</thead>
	<tbody>
		<% @sales.each do |sale| %>
		<tr>
			<td><%= link_to sale.item.name, pickup_path(sale.guid) %></td>
			<td><%= time_ago_in_words(sale.created_at) %> ago</td>
			<td><%= sale.buyer_email %></td> 
		</tr>
		<% end %>
 </tbody>
</table>

app/views/pages/adminpanel.html.erb
<div class="row">
	<h1 class="text-center">Adminpanel</h1>

	<div class="col-md-4">
		<h3 class="text-center">
			Items <%= link_to "New Item", new_item_path, class: "btn btn-primary btn-sm" %>
		</h3>
		<table class="table table-condensed">
			<%= render 'items' %>

	</div>

	<div class="col-md-4">
		<h3 class="text-center">Purchased</h3>
		<%= render 'purchased' %>

	</div>

	<div class="col-md-4">
		<h3 class="text-center">Sales</h3>
		<%= render 'sales' %>

	</div>

</div>

app/views/pages/home.html.erb
<div class="jumbotron">
    <h1>Welcome to Oneverr</h1>
    <p>The largest online Digital Market</p>

    <%= link_to "Item", items_path , class: "btn btn-primary" %>
    <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary" %>


</div>

<div class="row">

  <%= render @items %>

</div>

app/views/transactions/pickup.html.erb
<div class="row text-center">
	<br>
	<h1>Congratulations! Nd Thanks for buying</h1>
	<h3>I dont not know what to do from here, you are screwed! LOL! :}		</h3>
	<br>

</div>